#ifndef CARTOON_MAKER_UI_CONTEXT_MENU_MAINPOINTCONTEXTMENU_H_
#define CARTOON_MAKER_UI_CONTEXT_MENU_MAINPOINTCONTEXTMENU_H_

#include <QMenu>

class MainPointContextMenu : QMenu {
  // TODO: Create this class
 public:
 private:

};

#endif //CARTOON_MAKER_UI_CONTEXT_MENU_MAINPOINTCONTEXTMENU_H_
