#ifndef CARTOON_MAKER_LOGIC_IMAGES_FACTORY_IMAGEFACTORY_H_
#define CARTOON_MAKER_LOGIC_IMAGES_FACTORY_IMAGEFACTORY_H_

class ImageFactory {
  // TODO: Crate ImageFactory class
};

#endif //CARTOON_MAKER_LOGIC_IMAGES_FACTORY_IMAGEFACTORY_H_
