#ifndef CARTOON_MAKER_ENTITIES_BODY_FACTORY_BODYFACTORY_H_
#define CARTOON_MAKER_ENTITIES_BODY_FACTORY_BODYFACTORY_H_

class BodyFactory {
  // TODO: Create BodyFactory class
};

#endif //CARTOON_MAKER_ENTITIES_BODY_FACTORY_BODYFACTORY_H_
